/**
 * @module middleware
 *
 * Express middleware functions for the Nexus AI Gateway.
 *
 * Provides request logging, unique request-ID generation,
 * CORS configuration for local-network access, and a
 * centralised JSON error handler.
 */

import { Request, Response, NextFunction } from 'express';
import crypto from 'crypto';

/* ------------------------------------------------------------------ */
/*  Request Logger                                                     */
/* ------------------------------------------------------------------ */

/**
 * Express middleware that logs every incoming request.
 *
 * Each log line includes a `[Nexus]` prefix followed by the
 * ISO-8601 timestamp, HTTP method, request URL, and the
 * client's IP address.
 *
 * @param req  - The incoming Express request.
 * @param res  - The outgoing Express response.
 * @param next - Callback to pass control to the next middleware.
 */
export function requestLogger(
  req: Request,
  res: Response,
  next: NextFunction,
): void {
  const timestamp: string = new Date().toISOString();
  const method: string = req.method;
  const url: string = req.originalUrl || req.url;
  const clientIp: string = req.ip || req.socket.remoteAddress || 'unknown';

  console.log(`[Nexus] ${timestamp} ${method} ${url} - ${clientIp}`);
  next();
}

/* ------------------------------------------------------------------ */
/*  Request-ID Middleware                                               */
/* ------------------------------------------------------------------ */

/**
 * Express middleware that generates a unique request identifier.
 *
 * A UUID v4 is created via `crypto.randomUUID()`, attached to the
 * request object as `(req as any).requestId`, and also set as the
 * `X-Request-Id` response header so callers can correlate responses
 * with their requests.
 *
 * @param req  - The incoming Express request.
 * @param res  - The outgoing Express response.
 * @param next - Callback to pass control to the next middleware.
 */
export function requestIdMiddleware(
  req: Request,
  res: Response,
  next: NextFunction,
): void {
  const requestId: string = crypto.randomUUID();
  (req as any).requestId = requestId;
  res.setHeader('X-Request-Id', requestId);
  next();
}

/* ------------------------------------------------------------------ */
/*  CORS Configuration                                                 */
/* ------------------------------------------------------------------ */

/**
 * CORS configuration object that permits access from any origin.
 *
 * This is intentionally permissive to support local-network
 * access scenarios where the gateway is consumed by devices on
 * the same LAN.
 */
export const corsConfig: {
  readonly origin: string;
  readonly methods: readonly string[];
  readonly allowedHeaders: readonly string[];
} = {
  origin: '*',
  methods: ['GET', 'POST', 'OPTIONS'],
  allowedHeaders: [
    'Content-Type',
    'Authorization',
    'X-Nexus-Task',
    'X-Nexus-Max-Cost',
    'X-Nexus-Prefer-Provider',
    'X-Nexus-Skip-Refinement',
  ],
} as const;

/* ------------------------------------------------------------------ */
/*  Error Handler                                                      */
/* ------------------------------------------------------------------ */

/**
 * Shape of an error that optionally carries an HTTP status code.
 */
interface HttpError extends Error {
  /** Optional HTTP status code to return to the client. */
  statusCode?: number;
}

/**
 * Centralised Express error-handling middleware.
 *
 * Logs the error to the console and responds with a structured
 * JSON payload that includes the numeric error code, a human-readable
 * message, and the request ID (if one was generated by
 * {@link requestIdMiddleware}).
 *
 * @param err  - The error thrown or passed via `next(err)`.
 * @param req  - The incoming Express request.
 * @param res  - The outgoing Express response.
 * @param _next - Callback to the next error handler (unused but
 *               required by Express to identify this as an error handler).
 */
export function errorHandler(
  err: HttpError,
  req: Request,
  res: Response,
  _next: NextFunction,
): void {
  const statusCode: number = err.statusCode || 500;
  const message: string = err.message || 'Internal server error';
  const requestId: string | undefined = (req as any).requestId;

  console.error(
    `[Nexus] Error ${statusCode}: ${message}`,
    requestId ? `(requestId: ${requestId})` : '',
  );

  res.status(statusCode).json({
    error: {
      code: statusCode,
      message,
      requestId,
    },
  });
}
